language: php

php:
    - 5.4
    - 5.5

sudo: false

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=3.6 COVERAGE=1

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - if [[ $COVERAGE ]]; then vendor/bin/phpunit --coverage-clover coverage.xml environmentcheck/tests; fi
  - if [[ ! $COVERAGE ]]; then vendor/bin/phpunit environmentcheck/tests; fi

after_success:
  - if [[ $COVERAGE ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
